<?php

namespace backend\modules\smsgo\models\search;

class SmsBatchMessage extends \yii\base\Model
{
    public $user_sms_id;
    public $to;
    public $text;

    public function init()
    {
        $this->user_sms_id = \Yii::$app->security->generateRandomString(6);
        parent::init();
    }

    public function beforeValidate()
    {
        $this->prepare();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['to'], 'string', 'max' => 12, 'min' => 12],
            ['text', 'string']
        ];
    }

    private function prepare()
    {
        $this->to = preg_replace("/[^\d]/", "", $this->to);
    }

}