<?php

namespace backend\modules\smsgo\controllers;

use yii\helpers\Console;

class MigrateController extends \yii\console\controllers\MigrateController
{
    public $migrationPath = ['@backend/modules/smsgo/migrations'];
    public $migrationTable = '{{%smsgo_migration}}';

    public function beforeAction($action)
    {
        if (!$this->request->isConsoleRequest) {
            echo "<!-- Created by Olimjon Gofurov --!>";
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionUp($limit = 0)
    {
        Console::output("****************************");
        Console::output("* SMSGO by Olimjon Gofurov *");
        Console::output("****************************");
        return parent::actionUp($limit);
    }
}